### ISSUE TITLE
Validação de sintáxe no corpo das requisições

### ISSUE THREAD

**Issue by alexradavelli** [DRodrigues17/estacionamento-API#5]
É interessante utilizar a API de validação do Java (javax.validation) para implementar a validação da sintáxe de atributos dos corpos das requisições, especialmente em requisições POST e PUT. Neste contexto, é possível validar:

- Atributos obrigatórios
- Tamanho dos atributos
- Formato dos atributos
- Domínio dos valores válidos para os atributos
- Entre outros casos

**Comment by DRodrigues17** [comment]
professor, eu tenho noção de como por isso na classe de modelo, aí só pra confirmar, na camada de controller eu botaria a notação "@Valid" ?
